package com.myspace.demo1;

import java.util.List;

global com.myspace.mysql.InitDevice initDevice;

function boolean toBoolean(int val) {
    if (val == 0) return false;
    return true;
}

rule "init device"
	dialect "mvel"
	
	when
	    $alert : Alert(description == "INIT")
	then
		System.out.println("Executed Rule: " + drools.getRule().getName() );
	    retract( $alert );
	    int i = 0;
		List list = null;
	  	int limit = 5;
		do {
			list = null; // reset list before continuing
			list = initDevice.readData(limit, limit * i);
			i += 1;
			System.out.println("Size of list returned: " + list.size());
			for (Object obj : list) {
			    Switch sw = (Switch) obj;
				System.out.println(sw.getDateTime() + ": " + sw.getSite() + "." + sw.getAssetType() + "." + sw.getAsset_id() +
						"." + sw.getAttribute() + "." + sw.isValue());
				insert(sw);
			}
		} while ((list != null) && (list.size() == limit))
	    initDevice.close();
end
	
rule "update status"
	dialect "mvel"
	salience 10
	
	when
	    $alert : Switch()
	    Switch ( site == $alert.site, assetType == $alert.assetType, asset_id == $alert.asset_id, dateTime > $alert.dateTime )
	then
	    System.out.println("Executed Rule: " + drools.getRule().getName() );
	    retract( $alert )
	
end
/*
rule "alert condition 1"
	dialect "mvel"


    // IF (CYD.CB.552.POS=0 || CYD.DIS.556.POS=0 || (CYD.DIS.553.POS=0 && CYD.DIS.555.POS=0) )
	when
	  not Alert(description == "alert condition 1")
	  (
	    // CYD.CB.552.POS=0 
		Switch( site == "CYD", assetType == "CB", asset_id == 552, attribute == "POS", value == false)
		or
		// CYD.DIS.556.POS=0
		Switch( site == "CYD", assetType == "DIS", asset_id == 556, attribute == "POS", value == false)
        or
        // CYD.DIS.553.POS=0 && CYD.DIS.555.POS=0
        (
            Switch( site == "CYD", assetType == "DIS", asset_id == 553, attribute == "POS", value == false)
		and
		// CYD.DIS.556.POS=0
		    Switch( site == "CYD", assetType == "DIS", asset_id == 555, attribute == "POS", value == false)
		)

	  )

	then
		System.out.println("Executed Rule: " + drools.getRule().getName() );
		// The insert statement is not needed in your demo, only use it for running the Test Scenarios
		insert( new Alert(true, "alert condition 1" ));
		
		// add the notification to the Alert UI below
end

rule "alert condition 1 eased"
	dialect "mvel"


    // IF (CYD.CB.552.POS=0 || CYD.DIS.556.POS=0 || (CYD.DIS.553.POS=0 && CYD.DIS.555.POS=0) )
	when
	   $alert : Alert(description == "alert condition 1")
	   not (
	    // CYD.CB.552.POS=0 
		Switch( site == "CYD", assetType == "CB", asset_id == 552, attribute == "POS", value == false)
		or
		// CYD.DIS.556.POS=0
		Switch( site == "CYD", assetType == "DIS", asset_id == 556, attribute == "POS", value == false)
        or
        // CYD.DIS.553.POS=0 && CYD.DIS.555.POS=0
        (
            Switch( site == "CYD", assetType == "DIS", asset_id == 553, attribute == "POS", value == false)
		and
		// CYD.DIS.556.POS=0
		    Switch( site == "CYD", assetType == "DIS", asset_id == 555, attribute == "POS", value == false)
		)

	  )

	then
		System.out.println("Executed Rule: " + drools.getRule().getName() );
		// The insert statement is not needed in your demo, only use it for running the Test Scenarios
		retract( $alert );
		
		// add the notification to the Alert UI below
end
*/
query "get alerts"
    alert : Alert()
end

